app7/urls.py
from django.urls import path
from . import views
app_name='app7'
urlpatterns=[
    path('hai', views.welcome),
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('home/<int:id>',views.home,name='home'),
    path('update/<int:id>',views.update,name='update'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('logout',views.logout,name='logout'),
    path('gallery',views.gallery,name='gallery'),
    path('viewphoto/<str:pk>',views.viewphoto,name='viewphoto'),
    
]

project9/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app7.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app7/models.py
from django.db import models

# Create your models here.
class Signup(models.Model):
    Name = models.CharField(max_length=20,default='')
    Age = models.IntegerField(default='')
    Place = models.CharField(max_length=20,default='')
    Photo = models.ImageField(upload_to='media/',null=True,blank=True,default='')
    Email = models.EmailField(default='')
    Password = models.CharField(max_length=8,default='')
class Photo(models.Model):
    image=models.ImageField(upload_to='media/',null=True,blank=True,default='')
    description=models.TextField()
    def __str__(self):
        return self.description   
  

app7/forms.py
from django import forms 
from . models import Signup 
class SignupForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    Confirmpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=Signup 
        fields='__all__'
class LoginForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=Signup
        fields=('Email','Password')
class UpdateForm(forms.ModelForm):
    class Meta():
        model=Signup 
        fields=('Name','Age','Photo','Place','Email',) 
class ChangepasswordForm(forms.Form):
     Oldpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)
     Newpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)
     Newconfirmpassword=forms.CharField(widget=forms.PasswordInput,max_length=8)           
           
                

app7/views.py
from django.http.response import HttpResponse
from django.shortcuts import render,redirect
from django.contrib import messages
from . models import Photo, Signup
from . forms import LoginForm, SignupForm, UpdateForm,ChangepasswordForm
from django.contrib.auth import logout as logouts
# Create your views here.
def welcome(request):
    return HttpResponse("welcome django")
def index(request):
    var5="lavanya"
    return render(request,'index.html',{'var5':var5})
def signup(request):
    if request.method=='POST':
        f=SignupForm(request.POST or None,request.FILES or None)
        if f.is_valid():
            name=f.cleaned_data['Name']
            age=f.cleaned_data['Age']
            place=f.cleaned_data['Place']
            photo=f.cleaned_data['Photo']
            email=f.cleaned_data['Email']
            password=f.cleaned_data['Password']
            cpassword=f.cleaned_data['Confirmpassword']
            user=Signup.objects.filter(Email=email).exists()
            if user:
                messages.warning(request,"user already exists")
                return redirect('/signup')
            elif password!=cpassword:
                messages.warning(request,"password does not matches")
                return redirect('/signup')
            else:
                tab=Signup(Name=name,Age=age,Place=place,Photo=photo,Email=email,Password=password)
                tab.save()
                messages.success(request,"account created successfully")
                return redirect('/')

    else:
        f=SignupForm()
    return render(request,'signup.html',{'form':f}) 
def login(request):
    if request.method=='POST':
        f=LoginForm(request.POST)
        if f.is_valid():
            email=f.cleaned_data['Email']
            password=f.cleaned_data['Password']
            user=Signup.objects.get(Email=email)
            if not user:
                messages.warning(request,"user does not exists")
                return redirect('/login')
            elif user.Password!=password:
                messages.warning(request,"Password does not exists")
                return redirect('/login')
            else:
                messages.success(request,"login successfull")
                return redirect('/home/%s' % user.id)
    else:
        f=LoginForm()
    return render(request,'login.html',{'form':f})
def home(request,id):
    user=Signup.objects.get(id=id)
    return render(request,'home.html',{'user':user})
def update(request,id):
    user=Signup.objects.get(id=id)
    if request.method=='POST':
       f=UpdateForm(request.POST or None,request.FILES or None,instance=user)
       if f.is_valid():
            name=f.cleaned_data['Name']
            age=f.cleaned_data['Age']
            place=f.cleaned_data['Place']
            photo=f.cleaned_data['Photo']
            email=f.cleaned_data['Email']
            f.save()
            return redirect('/home/%s' % user.id)
    else:
        f=UpdateForm(instance=user)
    return render(request,'update.html',{'user':user,'form':f})
def changepassword(request,id):
    user=Signup.objects.get(id=id)
    if request.method=='POST':
         f=ChangepasswordForm(request.POST or None,request.FILES or None) 
         if f.is_valid():
           opassword=f.cleaned_data['Oldpassword']
           npassword=f.cleaned_data['Newpassword']
           ncpassword=f.cleaned_data['Newconfirmpassword']
           if user.Password!=opassword:
               messages.warning(request,"incorrect password")
               return redirect('/changepassword/%s' % user.id)
           elif npassword!=ncpassword:
               messages.warning(request,"password mismatch")
               return redirect('/changepassword/%s' % user.id)
           else:
               user.Password=npassword
               user.save()
               messages.success(request,"password changed successfully")
               return redirect('/home/%s' % user.id)
    else:
        f=ChangepasswordForm()
    return render(request,'changepassword.html',{'user':user,'form':f})
def logout(request):
    logouts(request)
    messages.success(request,"logout successfully")
    return redirect('/')
def gallery(request):
    photos=Photo.objects.all()
    return render(request,'gallery.html',{'photos':photos})
def viewphoto(request,pk):
    photo=Photo.objects.get(id=pk)
    return render(request,'photo.html',{'photo':photo})

        
               
             
        
            
      
        
    
        
        
        
                

        

app7/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
<form action="" method="POST">
{% csrf_token %}
<table>
<tr>
<td>{{ form.as_table }}</td>
</tr>
</table>
<input type="submit" value="changepassword">
</form>
</body>
</html>

app7/templates/gallery.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="if-edge">
        <meta name="viewport" content="width-device-width,initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    </head>
    <body>
    <div class="container-fluid">
    <div class="row">
    {% for photo in photos %}   
    <div class="col-md-4">
    <img src="{{ photo.image.url }}" height="300px" width="300px">
    <div>
    <p style="{font-weight:bold; color:red; text-align:center;">picture</p>
    </div>
    <a href="{% url 'app7:viewphoto' photo.id %}" class=" btn btn-default btn-sm">View</a>
    </div>
    {% endfor %}
    </div>
    </div>
    </body>
    </html>









        
        

app7/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
</head>
<body>
{% for msg in messages %}



           <div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Hey!</strong>{{ msg }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> {% endfor %}
{{ user.Name }}
{{ user.Email }}
<img src="{{  user.Photo.url }}" height="100" width="100"><br>
<a href="{% url 'app7:update' user.id %}">UPDATE</a>
<a href="{% url 'app7:changepassword' user.id %}">CHANGEPASSWORD</a>
<a href="{% url 'app7:logout' user.id %}">LOGOUT</a>
</body>

app7/templates/index.html
<!DOCTYPE html>
<html lang ="en">
<head>
</head>
<body>
<h1>welcome project9!!</h1>
<h2>{{ data }}</h2>
<a href="{% url 'app7:signup' %}">SIGNUP</a>
<a href="{% url 'app7:login' %}">LOGIN</a>
<a href="{% url 'app7:gallery' %}">GALLERY</a>
</body>
</html>

app7/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
{% for msg in messages %}



           <div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Hey!</strong>{{ msg }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> {% endfor %}
<form action="" method="POST"> 
{% csrf_token %} 
<table>
<tr>
<td>{{ form.as_table }}</td>
</tr>
<table>
<input type="submit" value="login">
</form>
</body>
</html>

app7/templates/photo.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="if-edge">
        <meta name="viewport" content="width-device-width,initial-scale=1.0">
        <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
    <div class="container-fluid">
    <div class="row justify-content-center"> 
    <div class="col-md-4">
    <div>
    <img src="{{ photo.image.url }}" height="300px" width="300px">
    <p style="{font-weight:bold; font-size:20px; color:red;">{{ photo.description }}
    </p>
    </div>
    </div>
    </div>
    </div>
    </body>
    </html>

         

app7/templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
</head>
<body>
{% for msg in messages %}



           <div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Hey!</strong>{{ msg }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div> {% endfor %}
<form action="" method="POST"> <enctype="multipart/form_data">
{% csrf_token %} 
<table>
<tr>
<td>{{ form.as_table }}</td>
</tr>
<table>
<input type="submit" value="Signup">
</form>
</body>
</html>

app7/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    {% for msg in messages %}



    <div class="alert alert-success alert-dismissible fade show" role="alert">
<strong>Hey!</strong>{{ msg }}
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">&times;</span>
</button>
</div> {% endfor %}        
<form action="" method="POST"> 
{% csrf_token %}
<table>
<tr>
<td>{{ form.as_table }}</td>
</tr>
</table>
<input type="submit" value="update">
</form>
</body>
</html>